#!/bin/sh

# Generate code coverage reports with hpc.
# Non-relevant modules are excluded from the final reports.

exclude=`for x in Main Properties Displayable Commands StringConn; do \
    echo --exclude=$x ; done`

runhaskell Setup configure -f test -f coverage --disable-optimization \
    && runhaskell Setup build && dist/build/test/test >/dev/null \
    && hpc markup test.tix --destdir=report $exclude \
    && hpc report test.tix $exclude \
    || echo "Please run 'Setup clean' and try again"
