#!/bin/sh

# Run tests and signal error on failure.

runhaskell Setup configure -f test --disable-optimization \
    && runhaskell Setup build \
    && runhaskell Setup configure \
    && runhaskell Setup haddock --hyperlink \
    && dist/build/test/test $1 | tee test.log \
    || exit 1

if `fgrep -q Falsifiable test.log` \
    || `fgrep -q '*** FAILURE ***' test.log` ; then
    #echo "Failure detected!"
    exit 1
else
    rm test.log
fi
