#!/bin/sh

# Run tests and signal error on failure.

runhaskell Setup configure -f test --disable-optimization \
    && runhaskell Setup build \
    && runhaskell Setup configure \
    && runhaskell Setup haddock \
    && dist/build/test/test | tee test.log

if `grep Falsifiable test.log >/dev/null` \
    || `grep "\*\*\* FAILURE \*\*\*" test.log >/dev/null` ; then
    #echo "Failure detected!"
    exit 1
else
    rm test.log
fi
