#!/bin/sh

# Run tests and signal error on failure.
# Saves output in 'test.log', unless no failures are detected.

runhaskell -itests tests/Main.hs | tee test.log
if $(grep Falsifiable test.log >/dev/null) \
    || $(grep "\*\*\* FAILURE \*\*\*" test.log >/dev/null) ; then
    #echo "Failure detected!"
    exit 1
else
    rm test.log
fi
#runhaskell Setup configure --disable-optimization -f test && \
#runhaskell Setup build && runhaskell Setup haddock
